spring:
  profiles:
    active: dev
  data:
    mongodb:
      authentication-database: admin
      username: username
      password: password
      database: competitions
      port: 27017
      host: localhost
server:
  error:
    whitelabel:
      enabled: true
