spring:
  data:
    mongodb:
      username: root
      password: dev

  datasource:
    url: 'jdbc:sqlserver://localhost;databaseName=competition-storage;'
    username: competition-storage
    password: competition-storage
    driver-class-name: 'com.microsoft.sqlserver.jdbc.SQLServerDriver'
    #url: 'jdbc:h2:file:./database/competition-storage;'
    #driver-class-name: 'org.h2.Driver'
    #username: root
    #password: dev
  jpa:
#    show-sql: true
    database-platform: 'org.hibernate.dialect.SQLServer2012Dialect'
    #database-platform: 'org.hibernate.dialect.H2Dialect'
    hibernate:
      ddl-auto: update

#  h2:
#    console:
#      enabled: true
#      path: '/h2-console'

server:
  error:
    include-stacktrace: always

logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG

  file:
    name: "dev.log"
