spring:
  profiles:
    active: dev
  data:
    mongodb:
      authentication-database: admin
      username: username
      password: password
      database: competitions
      port: 27017
      host: localhost


  main:
    allow-bean-definition-overriding: true
  error:
    whitelabel:
      enabled: true
  jpa:
    generate-ddl: true

springdoc:
  api-docs:
    path: '/api-docs'
  swagger-ui:
    path: '/api-docs-ui.html'
