# Use root/example as user/password credentials
version: '3.1'

services:
  activemq:
    container_name: activemq-artemis
    image: vromero/activemq-artemis
    restart: always
    environment:
      ARTEMIS_USERNAME: dev
      ARTEMIS_PASSWORD: dev
    ports:
      - 8161:8161
      - 61616:61616
    volumes:
      - data:/var/lib/artemis/data
      - etc:/var/lib/artemis/etc

volumes:
  data:
  etc: