spring:
  profiles:
    active: dev
  data:
    mongodb:
      authentication-database: admin
      username: username
      password: password
      database: competitions
      port: 27017
      host: localhost

  main:
    allow-bean-definition-overriding: true
  error:
    whitelabel:
      enabled: true
  jpa:
    generate-ddl: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 16MB
      max-request-size: 16MB

  artemis:
    mode: embedded
    host: localhost
    port: 61616
    user: dev
    password: dev
    embedded:
      enabled: true

  jms:
    template:
      default-destination: my-queue-1

axon:
  serializer:
    general: jackson
    events: jackson
    messages: jackson

springdoc:
  api-docs:
    path: '/api-docs'
  swagger-ui:
    path: '/api-docs-ui.html'

logging:
  level:
    org:
      apache:
        activemq:
          audit:
            base: WARN
            message: WARN
